owner: Raznar-Hosting 
repo: uptime-monitor 

assignees:
  - NotYusta
  - KJosh541

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

sites:
  - name: Websites
    check: "tcp-ping"
    url: $PROXY_1_URL
    port: 22
  - name: GAME-C-SGP1
    check: "tcp-ping"
    url: $PROXY_1_URL
    port: 10001
  - name: GAME-C-SGP2
    check: "tcp-ping"
    url: $PROXY_1_URL
    port: 10002
  - name: GAME-PVE-SGP1
    check: "tcp-ping"
    url: $PROXY_1_URL
    port: 10003
    
user-agent: raznar-hosting

status-website:
  cname: uptime.raznar.id
  logoUrl: https://cdn.discordapp.com/attachments/776806054394593321/899842944599728138/20210225_100806.png
  name: Raznar
  status-website:
    apiBaseUrl: https://api.github.com
    theme: night
  introTitle: "Raznar Hosting - Uptime"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

commitMessages:
  commitAuthorName: "NotYusta"
  commitAuthorEmail: "support@raznar.id"
