owner: Raznar-Hosting 
repo: uptime-monitor 

assignees:
  - hansputera

sites:
  - name: Main Website
    url: https://raznar.id
  - name: Game Hosting Panel
    url: https://game.hosting.raznar.id
  - name: App Hosting Panel
    url: https://app.hosting.raznar.id
    
user-agent: raznar-hosting

status-website:
  #cname: up.raznar.id
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Raznar
  status-website:
    apiBaseUrl: https://api.github.com
    theme: night
  introTitle: "Raznar Hosting Uptime Pages"
  introMessage: "Hey!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Discord
      href: https://raznar.id/discord

commitMessages:
  commitAuthorName: "Raznar Uptime"
  commitAuthorEmail: "support@raznar.id"
