owner: Raznar-Hosting 
repo: uptime-monitor 

assignees:
  - hansputera
  - NotYusta
  - KJosh541

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

sites:
  - name: Main Website
    url: https://raznar.id
  - name: Game Hosting Panel
    url: https://game.hosting.raznar.id
  - name: App Hosting Panel
    url: https://app.hosting.raznar.id
    
user-agent: raznar-hosting

status-website:
  cname: up.raznar.id
  logoUrl: https://cdn.discordapp.com/attachments/776806054394593321/899842944599728138/20210225_100806.png
  name: Raznar
  status-website:
    apiBaseUrl: https://api.github.com
    theme: night
  introTitle: "Raznar Hosting Uptime Pages"
  introMessage: "Hey!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Discord
      href: https://raznar.id/discord

commitMessages:
  commitAuthorName: "hansputera"
  commitAuthorEmail: "hanif@tslab.site"
