owner: Raznar-Hosting 
repo: uptime-monitor 

assignees:
  - NotYusta
  - KJosh541

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

sites:
  - name: Main Website
    url: https://raznar.id
  - name: Panel Control
    url: https://console-ptero.raznar.id
  - name: phpmyAdmin
    check: "tcp-ping"
    url: $PROXY_1_URL
    port: 443
  - name: GAME-C-SGP1
    url: https://game-c-sgp1.raznar.id
  - name: GAME-C-SGP2
    url: https://game-c-sgp2.raznar.id
  - name: GAME-PVE-SGP1
    url: https://game-pve-sgp1.raznar.id
    
user-agent: raznar-hosting

status-website:
  cname: uptime.raznar.id
  logoUrl: https://cdn.discordapp.com/attachments/776806054394593321/899842944599728138/20210225_100806.png
  name: Raznar
  status-website:
    apiBaseUrl: https://api.github.com
    theme: night
  introTitle: "Raznar Hosting Uptime Pages"
  introMessage: "Hey!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

commitMessages:
  commitAuthorName: "NotYusta"
  commitAuthorEmail: "support@raznar.id"
